language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin
  - rm -rf target/debug/incremental/{pharos,build_script_build}-*
  - rm -rf target/debug/.fingerprint/pharos-*
  - rm -rf target/debug/build/pharos-*
  - rm -rf target/debug/deps/libpharos-*
  - rm -rf target/debug/deps/pharos-*
  - rm -rf target/debug/{pharos,libpharos}.d
  - cargo clean -p pharos


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name  : linux stable check
      os    : linux
      rust  : stable
      script: cargo check


    - name  : linux nightly test everything
      os    : linux
      dist  : bionic
      rust  : nightly

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev         # for cargo-tarpaulin

      script:
        - bash ci/check.bash
        - bash ci/test.bash
        - bash ci/doc.bash
        - bash ci/coverage.bash


    - os    : osx
      script:
        - bash ci/test.bash


    - os    : windows
      script:
        - bash ci/test.bash


