language: rust
rust    :
  - stable
  - nightly

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


branches:
  only:
    - master
    - dev


matrix:

  include:

    - os: linux

      script:
        - cargo test
        - cargo test --release
        - cargo doc --no-deps --all-features


    - os: osx

      script:
        - cargo test



    - os: windows

      script:
        - cargo test



