name: Rust


on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev


jobs:

  linux-ci:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Install rust nightly

        run : |
          rustup toolchain add nightly
          rustup default nightly

      - name: Build
        run : cargo build  --all-features

      - name: Run tests
        run : cargo test  --all-features

      - name: Build --release
        run: cargo build  --all-features --release

      - name: Run tests --release
        run: cargo test  --all-features --release

      - name: Build docs
        run : cargo doc --no-deps --all-features

      # doesn't work on nightly until rustup can install the latest nightly which has clippy.
      #
      # - name: Run clippy
      #   run : cargo +stable clippy --all-features


  windows-ci:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v1

      - name: Install rust nightly

        run : |
          rustup toolchain add nightly
          rustup default nightly

      - name: Build
        run : cargo build  --all-features

      - name: Run tests
        run : cargo test  --all-features


  macos-ci:

    runs-on: macOS-latest

    steps:

      - uses: actions/checkout@v1

      - name: Install rust nightly

        run : |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh && sh rustup.sh -y
          source $HOME/.cargo/env
          rustup toolchain add nightly
          rustup default nightly

      - name: Build
        run : |
          source $HOME/.cargo/env
          cargo build  --all-features

      - name: Run tests
        run : |
          source $HOME/.cargo/env
          cargo test  --all-features

