name: Rust

on: [push, pull_request]

  branches: 
    - master
    - dev


jobs:

  cargo test:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

      - uses: actions/checkout@v1
      
      - name: Build
        run : cargo +nightly build  --all-features --verbose
        
      - name: Run tests
        run : cargo +nightly test  --all-features --verbose


  cargo test --release:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

      - uses: actions/checkout@v1
      
      - name: Build --release
        run: cargo +nightly build  --all-features --release --verbose
        
      - name: Run tests --release
        run: cargo +nightly test  --all-features --release --verbose


  cargo doc:

    runs-on: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v1
      
      - name: Build docs
        run : cargo doc --no-deps --all-features
        
